### ISSUE TITLE
No matching distribution found for requirements.txt

### ISSUE THREAD

**Issue by SrSands** [C0D3D3V/Moode_Downloader_2#2]
Im using Manjaro, and im getting a couple of errors:

$ pip3 install -r requirements.txt
`Collecting sentry_sdk>=0.13.5 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ba/0b/ba1655f0e9c248538b02322a979b5cd485156f5cc16ea34a3cff563527ee/sentry_sdk-0.14.0-py2.py3-none-any.whl (93kB)
     |████████████████████████████████| 102kB 2.7MB/s 
Requirement already satisfied: urllib3>=1.10.0 in /usr/lib/python3.8/site-packages (from sentry_sdk>=0.13.5->-r requirements.txt (line 1)) (1.25.7)
Collecting certifi (from sentry_sdk>=0.13.5->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
     |████████████████████████████████| 163kB 3.5MB/s 
Installing collected packages: certifi, sentry-sdk
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/certifi-2019.11.28.dist-info'
Consider using the `--user` option or check the permissions.

$ pip3 install --user requirements.txt

`Collecting requirements.txt
  ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt
`

**Comment by C0D3D3V** [comment]
If you want to install the requirements to your home directory, you must also execute the command with the -r parameter.
As: pip3 install --user -r requirements.txt

You can also install the requirements for all users, in which case you must run the command as root, preceded by `sudo'.


Among many distubutions the Python packages are also available in the package manager of the distubution. With Manjaro you should also find python_sentry_sdk in the AUR for download. Under certain circumstances this is more advisable than installing it via pip3. But that is up to you.

**Comment by SrSands** [comment]
i went for the AUR way. Thanks for the tip!

BTW any way to set a destination folder like in the older moodle?

**Comment by SrSands** [comment]
Also im getting files skipped. Seems strange.

**Comment by C0D3D3V** [comment]
Ok, Yes you can use the --path dest_path Option to set the destination. Or run the Downloader in a different working directory. That means, execute cd dest_path than python path_to_main.py 

or python main.py --path dest_path

**Comment by SrSands** [comment]
> main.py --path dest_path
I write a valid path destination (I used the command pwd to get it) and it returns:
`Error while trying to load the Configuration!`

**Comment by C0D3D3V** [comment]
You also need to use the `--path` in addition to `--init` option. So that a configuration file gets generated. Or you just copy the old generated configuration (and the .db file) to the new directory.
I will change the readme late this day, so that it is more clear. :)
